# Generated by Django 2.2.12 on 2020-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200528_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
