# Generated by Django 2.2.12 on 2020-06-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_attendance_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], default='-', max_length=1, null=True),
        ),
    ]
