# Generated by Django 2.2.12 on 2020-06-11 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200611_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
